Repository kalviumcommunity/S72_Anant_Capstone_AICareerGuidance, pull requests merged in 2025-06, with the labels that each got.

#35 added the test logic and about page
  AI/.gitignore
  AI/ai.js
  AI/package-lock.json
  AI/package.json
  Backend/controller/ai.js
  Backend/middleware/auth.js
  Backend/models/test.model.js
  Backend/models/user.model.js
  Backend/package-lock.json
  Backend/package.json
  Backend/routes/ai.js
  Backend/routes/auth.js
  Backend/routes/questions.js
  Backend/routes/user.js
  Backend/server.js
  Backend/uploads/1751025994892.png
  Backend/uploads/1751026079530.jpg
  Backend/uploads/1751028214629.jpg
  Frontend/src/App.jsx
  Frontend/src/Components/AuthProvider.jsx
  Frontend/src/Components/ProtectedRoute.jsx
  Frontend/src/Components/footer.jsx
  Frontend/src/Components/header.jsx
  Frontend/src/Components/nav.jsx
  Frontend/src/Pages/Profile.jsx
  Frontend/src/Pages/aboutMe.jsx
  Frontend/src/Pages/landing.jsx
  Frontend/src/Pages/login.jsx
  Frontend/src/Pages/signup.jsx
  Frontend/src/Pages/test.jsx
  Frontend/src/Routes/routes.js
Labels: Review effort 4/5, Possible security concern

#38 post api used
  Backend/routes/auth.js
Labels: Review effort 3/5, Possible security concern

#37 Added BackToTop.jsx
  Frontend/src/App.jsx
  Frontend/src/Components/BackToTop.jsx
Labels: Review effort 2/5

#36 Added Loding Spinner in Components
  Frontend/src/Components/LoadingSpinner.jsx
  Frontend/src/Components/ProtectedRoute.jsx
Labels: Review effort 2/5

#43 dockerized the project
  Backend/.dockerignore
  Backend/Dockerfile
  Frontend/.dockerignore
  Frontend/Dockerfile
  docker-compose.yml
Labels: Review effort 2/5

#44 put api used
  Backend/routes/user.js
Labels: Review effort 2/5
